export { organizationSchema } from './organization';
export { websiteSchema } from './website';
export { drivingSchoolSchema } from './drivingSchool';
export { breadcrumbsSchema } from './breadcrumbs';
export type { BreadcrumbItem } from './breadcrumbs';
export { serviceSchema, servicesListSchema, pageServiceSchema } from './service';
export { courseSchema } from './course';
export { howToSchema } from './howTo';
export type { HowToStepInput } from './howTo';
export { asfSeminarSchema } from './seminar';
export { personSchema } from './person';
export { faqSchema } from './faq';
export type { FaqItem } from './faq';
